id: op:P000783
initial_creation_type: input
source_metadata:
  id:
  source_src:     # resource in initial release
  source_bdr:     # BDRC Resource ID
  source_url: https://www.lotsawahouse.org/tibetan-masters/geshe-langri-thangpa/eight-verses-training-mind
  title: Eight Verses of Training the Mind
  author: Geshe Langri Thangpa
  lang: en